name: Inputs demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the env to deploy
        required: true
        default: dev
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the App
        run: echo "deploying the Application to ${{ inputs.environment}}"
  
    
    
