name: Inputs demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the env to deploy
        required: true
        default: dev
        type: choice
        options:
        - dev
        - test
        - prod
      artfat_tag:
        description: choose the git tag to depoly
        required: true
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the App
        run: echo "deploying the {{inputs.artfat_tag}} Application to ${{ inputs.environment}}"
  
    
    
