name: outputs-jobslevel
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.step 1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        id: step 1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        run: echo "we are deploy the app with version ${{ needs.build.outputs.version}}
